/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.1.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnswerDistribution {
  'count' : bigint,
  'optionIndex' : bigint,
  'isCorrect' : boolean,
}
export type AnswerSubmission = { 'text' : string } |
  { 'slider' : bigint } |
  { 'options' : Array<bigint> };
export interface ArchivedPlayer {
  'displayName' : string,
  'answers' : Array<ArchivedPlayerAnswer>,
  'rank' : bigint,
  'score' : bigint,
  'avatarIndex' : bigint,
}
export interface ArchivedPlayerAnswer {
  'selectedOptions' : Array<bigint>,
  'isCorrect' : boolean,
  'questionIndex' : bigint,
  'pointsEarned' : bigint,
  'sliderValue' : bigint,
  'textAnswer' : string,
}
export interface ArchivedQuestion {
  'text' : string,
  'sliderMax' : bigint,
  'sliderMin' : bigint,
  'questionType' : QuestionType,
  'acceptedAnswers' : Array<string>,
  'options' : Array<string>,
  'sliderCorrect' : bigint,
  'correctOptionIndices' : Array<bigint>,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type ExternalBlob = Uint8Array;
export type GamePhase = { 'answering' : null } |
  { 'scoreboard' : null } |
  { 'results' : null } |
  { 'ended' : null } |
  { 'lobby' : null } |
  { 'questionDisplay' : null } |
  { 'podium' : null };
export interface HostQuestionData {
  'theme' : string,
  'pointMode' : PointMode,
  'timeLimit' : bigint,
  'text' : string,
  'sliderMax' : bigint,
  'sliderMin' : bigint,
  'questionType' : QuestionType,
  'image' : [] | [ExternalBlob],
  'showQuestionToPlayers' : boolean,
  'acceptedAnswers' : Array<string>,
  'options' : Array<string>,
  'sliderCorrect' : bigint,
  'correctOptionIndices' : Array<bigint>,
  'imagePlacement' : ImagePlacement,
}
export type ImagePlacement = { 'background' : null } |
  { 'centered' : null };
export interface JoinResult {
  'playerToken' : bigint,
  'playerId' : bigint,
  'sessionId' : bigint,
  'avatarIndex' : bigint,
}
export interface LeaderboardEntry {
  'displayName' : string,
  'playerId' : bigint,
  'rank' : bigint,
  'score' : bigint,
  'currentStreak' : bigint,
  'avatarIndex' : bigint,
}
export interface LeaderboardResponse {
  'totalPlayers' : bigint,
  'entries' : Array<LeaderboardEntry>,
}
export interface PlayerQuestionData {
  'theme' : string,
  'timeLimit' : bigint,
  'text' : string,
  'sliderMax' : bigint,
  'sliderMin' : bigint,
  'questionType' : QuestionType,
  'image' : [] | [ExternalBlob],
  'showQuestionToPlayers' : boolean,
  'options' : Array<string>,
  'imagePlacement' : ImagePlacement,
}
export interface PlayerStateResponse {
  'status' : SessionStatus,
  'currentPhase' : GamePhase,
  'ownScore' : bigint,
  'ownDisplayName' : string,
  'lastHostHeartbeat' : bigint,
  'playerCount' : bigint,
  'players' : Array<PublicPlayerData>,
  'hasAnsweredCurrent' : boolean,
  'isLocked' : boolean,
  'lastPointsEarned' : bigint,
  'phaseStartTime' : bigint,
  'ownAvatarIndex' : bigint,
  'currentQuestionIndex' : bigint,
  'currentStreak' : bigint,
  'currentQuestion' : [] | [PlayerQuestionData],
  'lastAnswerCorrect' : [] | [boolean],
}
export type PointMode = { 'double' : null } |
  { 'none' : null } |
  { 'standard' : null };
export interface PostGameSummaryResponse {
  'questionSummaries' : Array<QuestionSummary>,
  'totalPlayers' : bigint,
  'totalQuestions' : bigint,
}
export interface Profile { 'name' : string }
export interface PublicPlayerData {
  'displayName' : string,
  'playerId' : bigint,
  'score' : bigint,
  'avatarIndex' : bigint,
}
export interface Question {
  'theme' : string,
  'pointMode' : PointMode,
  'timeLimit' : bigint,
  'text' : string,
  'isMultiSelect' : boolean,
  'sliderMax' : bigint,
  'sliderMin' : bigint,
  'questionType' : QuestionType,
  'image' : [] | [ExternalBlob],
  'showQuestionToPlayers' : boolean,
  'acceptedAnswers' : Array<string>,
  'options' : Array<string>,
  'sliderCorrect' : bigint,
  'correctOptionIndices' : Array<bigint>,
  'imagePlacement' : ImagePlacement,
}
export interface QuestionResultsResponse {
  'questionIndex' : bigint,
  'questionText' : string,
  'questionType' : QuestionType,
  'answerDistribution' : Array<AnswerDistribution>,
  'correctCount' : bigint,
  'options' : Array<string>,
  'totalAnswers' : bigint,
}
export interface QuestionSummary {
  'questionIndex' : bigint,
  'questionText' : string,
  'questionType' : QuestionType,
  'answerDistribution' : Array<AnswerDistribution>,
  'correctCount' : bigint,
  'correctPercent' : bigint,
  'options' : Array<string>,
  'totalAnswers' : bigint,
}
export type QuestionType = { 'quiz' : null } |
  { 'slider' : null } |
  { 'typeAnswer' : null } |
  { 'trueFalse' : null };
export interface Quiz {
  'id' : bigint,
  'title' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'questions' : Array<Question>,
}
export interface Report {
  'id' : bigint,
  'playedAt' : bigint,
  'playerCount' : bigint,
  'summary' : PostGameSummaryResponse,
  'players' : Array<ArchivedPlayer>,
  'questions' : Array<ArchivedQuestion>,
  'quizTitle' : string,
  'questionCount' : bigint,
}
export interface ReportSummary {
  'id' : bigint,
  'playedAt' : bigint,
  'playerCount' : bigint,
  'quizTitle' : string,
  'questionCount' : bigint,
}
export type Result = { 'ok' : null } |
  { 'err' : Error };
export interface SessionInfo { 'roomPin' : string, 'sessionId' : bigint }
export interface SessionStateResponse {
  'status' : SessionStatus,
  'currentPhase' : GamePhase,
  'roomPin' : string,
  'playerCount' : bigint,
  'players' : Array<PublicPlayerData>,
  'answerCount' : bigint,
  'isLocked' : boolean,
  'sessionId' : bigint,
  'phaseStartTime' : bigint,
  'autoAdvance' : boolean,
  'currentQuestionIndex' : bigint,
  'currentQuestion' : [] | [HostQuestionData],
  'questionCount' : bigint,
}
export type SessionStatus = { 'active' : null } |
  { 'ended' : null } |
  { 'lobby' : null };
export interface StreakEntry {
  'streak' : bigint,
  'displayName' : string,
  'avatarIndex' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'advancePhase' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkRoomPin' : ActorMethod<[string], boolean>,
  'createQuiz' : ActorMethod<[string, Array<Question>], bigint>,
  'createSession' : ActorMethod<[bigint], SessionInfo>,
  'deleteQuiz' : ActorMethod<[bigint], undefined>,
  'deleteReport' : ActorMethod<[bigint], undefined>,
  'endSession' : ActorMethod<[bigint], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[bigint], LeaderboardResponse>,
  'getPlayerLeaderboard' : ActorMethod<[string, bigint], LeaderboardResponse>,
  'getPlayerQuestionResults' : ActorMethod<
    [string, bigint, bigint],
    QuestionResultsResponse
  >,
  'getPlayerState' : ActorMethod<[string, bigint], PlayerStateResponse>,
  'getPlayerStreaks' : ActorMethod<[string, bigint], Array<StreakEntry>>,
  'getPostGameSummary' : ActorMethod<[bigint], PostGameSummaryResponse>,
  'getProfile' : ActorMethod<[], [] | [Profile]>,
  'getQuestionResults' : ActorMethod<[bigint, bigint], QuestionResultsResponse>,
  'getQuiz' : ActorMethod<[bigint], [] | [Quiz]>,
  'getQuizzes' : ActorMethod<[], Array<Quiz>>,
  'getReport' : ActorMethod<[bigint], [] | [Report]>,
  'getReports' : ActorMethod<[], Array<ReportSummary>>,
  'getSessionState' : ActorMethod<[bigint], SessionStateResponse>,
  'getStreaks' : ActorMethod<[bigint], Array<StreakEntry>>,
  'hostHeartbeat' : ActorMethod<[bigint], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinSession' : ActorMethod<[string, string], JoinResult>,
  'lockSession' : ActorMethod<[bigint, boolean], undefined>,
  'removePlayer' : ActorMethod<[bigint, bigint], undefined>,
  'setAutoAdvance' : ActorMethod<[bigint, boolean], undefined>,
  'setProfile' : ActorMethod<[string], undefined>,
  'startGame' : ActorMethod<[bigint], undefined>,
  'submitAnswer' : ActorMethod<[string, bigint, AnswerSubmission], undefined>,
  'updatePlayerName' : ActorMethod<[string, bigint, string], undefined>,
  'updateQuiz' : ActorMethod<[bigint, string, Array<Question>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];