/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.1.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PointMode = IDL.Variant({
  'double' : IDL.Null,
  'none' : IDL.Null,
  'standard' : IDL.Null,
});
export const QuestionType = IDL.Variant({
  'quiz' : IDL.Null,
  'slider' : IDL.Null,
  'typeAnswer' : IDL.Null,
  'trueFalse' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ImagePlacement = IDL.Variant({
  'background' : IDL.Null,
  'centered' : IDL.Null,
});
export const Question = IDL.Record({
  'theme' : IDL.Text,
  'pointMode' : PointMode,
  'timeLimit' : IDL.Nat,
  'text' : IDL.Text,
  'isMultiSelect' : IDL.Bool,
  'sliderMax' : IDL.Nat,
  'sliderMin' : IDL.Nat,
  'questionType' : QuestionType,
  'image' : IDL.Opt(ExternalBlob),
  'showQuestionToPlayers' : IDL.Bool,
  'acceptedAnswers' : IDL.Vec(IDL.Text),
  'options' : IDL.Vec(IDL.Text),
  'sliderCorrect' : IDL.Nat,
  'correctOptionIndices' : IDL.Vec(IDL.Nat),
  'imagePlacement' : ImagePlacement,
});
export const SessionInfo = IDL.Record({
  'roomPin' : IDL.Text,
  'sessionId' : IDL.Nat,
});
export const LeaderboardEntry = IDL.Record({
  'displayName' : IDL.Text,
  'playerId' : IDL.Nat,
  'rank' : IDL.Nat,
  'score' : IDL.Nat,
  'currentStreak' : IDL.Nat,
  'avatarIndex' : IDL.Nat,
});
export const LeaderboardResponse = IDL.Record({
  'totalPlayers' : IDL.Nat,
  'entries' : IDL.Vec(LeaderboardEntry),
});
export const AnswerDistribution = IDL.Record({
  'count' : IDL.Nat,
  'optionIndex' : IDL.Nat,
  'isCorrect' : IDL.Bool,
});
export const QuestionResultsResponse = IDL.Record({
  'questionIndex' : IDL.Nat,
  'questionText' : IDL.Text,
  'questionType' : QuestionType,
  'answerDistribution' : IDL.Vec(AnswerDistribution),
  'correctCount' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
  'totalAnswers' : IDL.Nat,
});
export const SessionStatus = IDL.Variant({
  'active' : IDL.Null,
  'ended' : IDL.Null,
  'lobby' : IDL.Null,
});
export const GamePhase = IDL.Variant({
  'answering' : IDL.Null,
  'scoreboard' : IDL.Null,
  'results' : IDL.Null,
  'ended' : IDL.Null,
  'lobby' : IDL.Null,
  'questionDisplay' : IDL.Null,
  'podium' : IDL.Null,
});
export const PublicPlayerData = IDL.Record({
  'displayName' : IDL.Text,
  'playerId' : IDL.Nat,
  'score' : IDL.Nat,
  'avatarIndex' : IDL.Nat,
});
export const PlayerQuestionData = IDL.Record({
  'theme' : IDL.Text,
  'timeLimit' : IDL.Nat,
  'text' : IDL.Text,
  'sliderMax' : IDL.Nat,
  'sliderMin' : IDL.Nat,
  'questionType' : QuestionType,
  'image' : IDL.Opt(ExternalBlob),
  'showQuestionToPlayers' : IDL.Bool,
  'options' : IDL.Vec(IDL.Text),
  'imagePlacement' : ImagePlacement,
});
export const PlayerStateResponse = IDL.Record({
  'status' : SessionStatus,
  'currentPhase' : GamePhase,
  'ownScore' : IDL.Nat,
  'ownDisplayName' : IDL.Text,
  'lastHostHeartbeat' : IDL.Int,
  'playerCount' : IDL.Nat,
  'players' : IDL.Vec(PublicPlayerData),
  'hasAnsweredCurrent' : IDL.Bool,
  'isLocked' : IDL.Bool,
  'lastPointsEarned' : IDL.Nat,
  'phaseStartTime' : IDL.Int,
  'ownAvatarIndex' : IDL.Nat,
  'currentQuestionIndex' : IDL.Nat,
  'currentStreak' : IDL.Nat,
  'currentQuestion' : IDL.Opt(PlayerQuestionData),
  'lastAnswerCorrect' : IDL.Opt(IDL.Bool),
});
export const StreakEntry = IDL.Record({
  'streak' : IDL.Nat,
  'displayName' : IDL.Text,
  'avatarIndex' : IDL.Nat,
});
export const QuestionSummary = IDL.Record({
  'questionIndex' : IDL.Nat,
  'questionText' : IDL.Text,
  'questionType' : QuestionType,
  'answerDistribution' : IDL.Vec(AnswerDistribution),
  'correctCount' : IDL.Nat,
  'correctPercent' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
  'totalAnswers' : IDL.Nat,
});
export const PostGameSummaryResponse = IDL.Record({
  'questionSummaries' : IDL.Vec(QuestionSummary),
  'totalPlayers' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
});
export const Profile = IDL.Record({ 'name' : IDL.Text });
export const Quiz = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'questions' : IDL.Vec(Question),
});
export const ArchivedPlayerAnswer = IDL.Record({
  'selectedOptions' : IDL.Vec(IDL.Nat),
  'isCorrect' : IDL.Bool,
  'questionIndex' : IDL.Nat,
  'pointsEarned' : IDL.Nat,
  'sliderValue' : IDL.Nat,
  'textAnswer' : IDL.Text,
});
export const ArchivedPlayer = IDL.Record({
  'displayName' : IDL.Text,
  'answers' : IDL.Vec(ArchivedPlayerAnswer),
  'rank' : IDL.Nat,
  'score' : IDL.Nat,
  'avatarIndex' : IDL.Nat,
});
export const ArchivedQuestion = IDL.Record({
  'text' : IDL.Text,
  'sliderMax' : IDL.Nat,
  'sliderMin' : IDL.Nat,
  'questionType' : QuestionType,
  'acceptedAnswers' : IDL.Vec(IDL.Text),
  'options' : IDL.Vec(IDL.Text),
  'sliderCorrect' : IDL.Nat,
  'correctOptionIndices' : IDL.Vec(IDL.Nat),
});
export const Report = IDL.Record({
  'id' : IDL.Nat,
  'playedAt' : IDL.Int,
  'playerCount' : IDL.Nat,
  'summary' : PostGameSummaryResponse,
  'players' : IDL.Vec(ArchivedPlayer),
  'questions' : IDL.Vec(ArchivedQuestion),
  'quizTitle' : IDL.Text,
  'questionCount' : IDL.Nat,
});
export const ReportSummary = IDL.Record({
  'id' : IDL.Nat,
  'playedAt' : IDL.Int,
  'playerCount' : IDL.Nat,
  'quizTitle' : IDL.Text,
  'questionCount' : IDL.Nat,
});
export const HostQuestionData = IDL.Record({
  'theme' : IDL.Text,
  'pointMode' : PointMode,
  'timeLimit' : IDL.Nat,
  'text' : IDL.Text,
  'sliderMax' : IDL.Nat,
  'sliderMin' : IDL.Nat,
  'questionType' : QuestionType,
  'image' : IDL.Opt(ExternalBlob),
  'showQuestionToPlayers' : IDL.Bool,
  'acceptedAnswers' : IDL.Vec(IDL.Text),
  'options' : IDL.Vec(IDL.Text),
  'sliderCorrect' : IDL.Nat,
  'correctOptionIndices' : IDL.Vec(IDL.Nat),
  'imagePlacement' : ImagePlacement,
});
export const SessionStateResponse = IDL.Record({
  'status' : SessionStatus,
  'currentPhase' : GamePhase,
  'roomPin' : IDL.Text,
  'playerCount' : IDL.Nat,
  'players' : IDL.Vec(PublicPlayerData),
  'answerCount' : IDL.Nat,
  'isLocked' : IDL.Bool,
  'sessionId' : IDL.Nat,
  'phaseStartTime' : IDL.Int,
  'autoAdvance' : IDL.Bool,
  'currentQuestionIndex' : IDL.Nat,
  'currentQuestion' : IDL.Opt(HostQuestionData),
  'questionCount' : IDL.Nat,
});
export const JoinResult = IDL.Record({
  'playerToken' : IDL.Nat,
  'playerId' : IDL.Nat,
  'sessionId' : IDL.Nat,
  'avatarIndex' : IDL.Nat,
});
export const AnswerSubmission = IDL.Variant({
  'text' : IDL.Text,
  'slider' : IDL.Nat,
  'options' : IDL.Vec(IDL.Nat),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'advancePhase' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkRoomPin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'createQuiz' : IDL.Func([IDL.Text, IDL.Vec(Question)], [IDL.Nat], []),
  'createSession' : IDL.Func([IDL.Nat], [SessionInfo], []),
  'deleteQuiz' : IDL.Func([IDL.Nat], [], []),
  'deleteReport' : IDL.Func([IDL.Nat], [], []),
  'endSession' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func([IDL.Nat], [LeaderboardResponse], ['query']),
  'getPlayerLeaderboard' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [LeaderboardResponse],
      ['query'],
    ),
  'getPlayerQuestionResults' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [QuestionResultsResponse],
      ['query'],
    ),
  'getPlayerState' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [PlayerStateResponse],
      ['query'],
    ),
  'getPlayerStreaks' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(StreakEntry)],
      ['query'],
    ),
  'getPostGameSummary' : IDL.Func(
      [IDL.Nat],
      [PostGameSummaryResponse],
      ['query'],
    ),
  'getProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getQuestionResults' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [QuestionResultsResponse],
      ['query'],
    ),
  'getQuiz' : IDL.Func([IDL.Nat], [IDL.Opt(Quiz)], ['query']),
  'getQuizzes' : IDL.Func([], [IDL.Vec(Quiz)], ['query']),
  'getReport' : IDL.Func([IDL.Nat], [IDL.Opt(Report)], ['query']),
  'getReports' : IDL.Func([], [IDL.Vec(ReportSummary)], ['query']),
  'getSessionState' : IDL.Func([IDL.Nat], [SessionStateResponse], ['query']),
  'getStreaks' : IDL.Func([IDL.Nat], [IDL.Vec(StreakEntry)], ['query']),
  'hostHeartbeat' : IDL.Func([IDL.Nat], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinSession' : IDL.Func([IDL.Text, IDL.Text], [JoinResult], []),
  'lockSession' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'removePlayer' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'setAutoAdvance' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'setProfile' : IDL.Func([IDL.Text], [], []),
  'startGame' : IDL.Func([IDL.Nat], [], []),
  'submitAnswer' : IDL.Func([IDL.Text, IDL.Nat, AnswerSubmission], [], []),
  'updatePlayerName' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'updateQuiz' : IDL.Func([IDL.Nat, IDL.Text, IDL.Vec(Question)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PointMode = IDL.Variant({
    'double' : IDL.Null,
    'none' : IDL.Null,
    'standard' : IDL.Null,
  });
  const QuestionType = IDL.Variant({
    'quiz' : IDL.Null,
    'slider' : IDL.Null,
    'typeAnswer' : IDL.Null,
    'trueFalse' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ImagePlacement = IDL.Variant({
    'background' : IDL.Null,
    'centered' : IDL.Null,
  });
  const Question = IDL.Record({
    'theme' : IDL.Text,
    'pointMode' : PointMode,
    'timeLimit' : IDL.Nat,
    'text' : IDL.Text,
    'isMultiSelect' : IDL.Bool,
    'sliderMax' : IDL.Nat,
    'sliderMin' : IDL.Nat,
    'questionType' : QuestionType,
    'image' : IDL.Opt(ExternalBlob),
    'showQuestionToPlayers' : IDL.Bool,
    'acceptedAnswers' : IDL.Vec(IDL.Text),
    'options' : IDL.Vec(IDL.Text),
    'sliderCorrect' : IDL.Nat,
    'correctOptionIndices' : IDL.Vec(IDL.Nat),
    'imagePlacement' : ImagePlacement,
  });
  const SessionInfo = IDL.Record({
    'roomPin' : IDL.Text,
    'sessionId' : IDL.Nat,
  });
  const LeaderboardEntry = IDL.Record({
    'displayName' : IDL.Text,
    'playerId' : IDL.Nat,
    'rank' : IDL.Nat,
    'score' : IDL.Nat,
    'currentStreak' : IDL.Nat,
    'avatarIndex' : IDL.Nat,
  });
  const LeaderboardResponse = IDL.Record({
    'totalPlayers' : IDL.Nat,
    'entries' : IDL.Vec(LeaderboardEntry),
  });
  const AnswerDistribution = IDL.Record({
    'count' : IDL.Nat,
    'optionIndex' : IDL.Nat,
    'isCorrect' : IDL.Bool,
  });
  const QuestionResultsResponse = IDL.Record({
    'questionIndex' : IDL.Nat,
    'questionText' : IDL.Text,
    'questionType' : QuestionType,
    'answerDistribution' : IDL.Vec(AnswerDistribution),
    'correctCount' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
    'totalAnswers' : IDL.Nat,
  });
  const SessionStatus = IDL.Variant({
    'active' : IDL.Null,
    'ended' : IDL.Null,
    'lobby' : IDL.Null,
  });
  const GamePhase = IDL.Variant({
    'answering' : IDL.Null,
    'scoreboard' : IDL.Null,
    'results' : IDL.Null,
    'ended' : IDL.Null,
    'lobby' : IDL.Null,
    'questionDisplay' : IDL.Null,
    'podium' : IDL.Null,
  });
  const PublicPlayerData = IDL.Record({
    'displayName' : IDL.Text,
    'playerId' : IDL.Nat,
    'score' : IDL.Nat,
    'avatarIndex' : IDL.Nat,
  });
  const PlayerQuestionData = IDL.Record({
    'theme' : IDL.Text,
    'timeLimit' : IDL.Nat,
    'text' : IDL.Text,
    'sliderMax' : IDL.Nat,
    'sliderMin' : IDL.Nat,
    'questionType' : QuestionType,
    'image' : IDL.Opt(ExternalBlob),
    'showQuestionToPlayers' : IDL.Bool,
    'options' : IDL.Vec(IDL.Text),
    'imagePlacement' : ImagePlacement,
  });
  const PlayerStateResponse = IDL.Record({
    'status' : SessionStatus,
    'currentPhase' : GamePhase,
    'ownScore' : IDL.Nat,
    'ownDisplayName' : IDL.Text,
    'lastHostHeartbeat' : IDL.Int,
    'playerCount' : IDL.Nat,
    'players' : IDL.Vec(PublicPlayerData),
    'hasAnsweredCurrent' : IDL.Bool,
    'isLocked' : IDL.Bool,
    'lastPointsEarned' : IDL.Nat,
    'phaseStartTime' : IDL.Int,
    'ownAvatarIndex' : IDL.Nat,
    'currentQuestionIndex' : IDL.Nat,
    'currentStreak' : IDL.Nat,
    'currentQuestion' : IDL.Opt(PlayerQuestionData),
    'lastAnswerCorrect' : IDL.Opt(IDL.Bool),
  });
  const StreakEntry = IDL.Record({
    'streak' : IDL.Nat,
    'displayName' : IDL.Text,
    'avatarIndex' : IDL.Nat,
  });
  const QuestionSummary = IDL.Record({
    'questionIndex' : IDL.Nat,
    'questionText' : IDL.Text,
    'questionType' : QuestionType,
    'answerDistribution' : IDL.Vec(AnswerDistribution),
    'correctCount' : IDL.Nat,
    'correctPercent' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
    'totalAnswers' : IDL.Nat,
  });
  const PostGameSummaryResponse = IDL.Record({
    'questionSummaries' : IDL.Vec(QuestionSummary),
    'totalPlayers' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
  });
  const Profile = IDL.Record({ 'name' : IDL.Text });
  const Quiz = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'questions' : IDL.Vec(Question),
  });
  const ArchivedPlayerAnswer = IDL.Record({
    'selectedOptions' : IDL.Vec(IDL.Nat),
    'isCorrect' : IDL.Bool,
    'questionIndex' : IDL.Nat,
    'pointsEarned' : IDL.Nat,
    'sliderValue' : IDL.Nat,
    'textAnswer' : IDL.Text,
  });
  const ArchivedPlayer = IDL.Record({
    'displayName' : IDL.Text,
    'answers' : IDL.Vec(ArchivedPlayerAnswer),
    'rank' : IDL.Nat,
    'score' : IDL.Nat,
    'avatarIndex' : IDL.Nat,
  });
  const ArchivedQuestion = IDL.Record({
    'text' : IDL.Text,
    'sliderMax' : IDL.Nat,
    'sliderMin' : IDL.Nat,
    'questionType' : QuestionType,
    'acceptedAnswers' : IDL.Vec(IDL.Text),
    'options' : IDL.Vec(IDL.Text),
    'sliderCorrect' : IDL.Nat,
    'correctOptionIndices' : IDL.Vec(IDL.Nat),
  });
  const Report = IDL.Record({
    'id' : IDL.Nat,
    'playedAt' : IDL.Int,
    'playerCount' : IDL.Nat,
    'summary' : PostGameSummaryResponse,
    'players' : IDL.Vec(ArchivedPlayer),
    'questions' : IDL.Vec(ArchivedQuestion),
    'quizTitle' : IDL.Text,
    'questionCount' : IDL.Nat,
  });
  const ReportSummary = IDL.Record({
    'id' : IDL.Nat,
    'playedAt' : IDL.Int,
    'playerCount' : IDL.Nat,
    'quizTitle' : IDL.Text,
    'questionCount' : IDL.Nat,
  });
  const HostQuestionData = IDL.Record({
    'theme' : IDL.Text,
    'pointMode' : PointMode,
    'timeLimit' : IDL.Nat,
    'text' : IDL.Text,
    'sliderMax' : IDL.Nat,
    'sliderMin' : IDL.Nat,
    'questionType' : QuestionType,
    'image' : IDL.Opt(ExternalBlob),
    'showQuestionToPlayers' : IDL.Bool,
    'acceptedAnswers' : IDL.Vec(IDL.Text),
    'options' : IDL.Vec(IDL.Text),
    'sliderCorrect' : IDL.Nat,
    'correctOptionIndices' : IDL.Vec(IDL.Nat),
    'imagePlacement' : ImagePlacement,
  });
  const SessionStateResponse = IDL.Record({
    'status' : SessionStatus,
    'currentPhase' : GamePhase,
    'roomPin' : IDL.Text,
    'playerCount' : IDL.Nat,
    'players' : IDL.Vec(PublicPlayerData),
    'answerCount' : IDL.Nat,
    'isLocked' : IDL.Bool,
    'sessionId' : IDL.Nat,
    'phaseStartTime' : IDL.Int,
    'autoAdvance' : IDL.Bool,
    'currentQuestionIndex' : IDL.Nat,
    'currentQuestion' : IDL.Opt(HostQuestionData),
    'questionCount' : IDL.Nat,
  });
  const JoinResult = IDL.Record({
    'playerToken' : IDL.Nat,
    'playerId' : IDL.Nat,
    'sessionId' : IDL.Nat,
    'avatarIndex' : IDL.Nat,
  });
  const AnswerSubmission = IDL.Variant({
    'text' : IDL.Text,
    'slider' : IDL.Nat,
    'options' : IDL.Vec(IDL.Nat),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'advancePhase' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkRoomPin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'createQuiz' : IDL.Func([IDL.Text, IDL.Vec(Question)], [IDL.Nat], []),
    'createSession' : IDL.Func([IDL.Nat], [SessionInfo], []),
    'deleteQuiz' : IDL.Func([IDL.Nat], [], []),
    'deleteReport' : IDL.Func([IDL.Nat], [], []),
    'endSession' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func([IDL.Nat], [LeaderboardResponse], ['query']),
    'getPlayerLeaderboard' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [LeaderboardResponse],
        ['query'],
      ),
    'getPlayerQuestionResults' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [QuestionResultsResponse],
        ['query'],
      ),
    'getPlayerState' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [PlayerStateResponse],
        ['query'],
      ),
    'getPlayerStreaks' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(StreakEntry)],
        ['query'],
      ),
    'getPostGameSummary' : IDL.Func(
        [IDL.Nat],
        [PostGameSummaryResponse],
        ['query'],
      ),
    'getProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getQuestionResults' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [QuestionResultsResponse],
        ['query'],
      ),
    'getQuiz' : IDL.Func([IDL.Nat], [IDL.Opt(Quiz)], ['query']),
    'getQuizzes' : IDL.Func([], [IDL.Vec(Quiz)], ['query']),
    'getReport' : IDL.Func([IDL.Nat], [IDL.Opt(Report)], ['query']),
    'getReports' : IDL.Func([], [IDL.Vec(ReportSummary)], ['query']),
    'getSessionState' : IDL.Func([IDL.Nat], [SessionStateResponse], ['query']),
    'getStreaks' : IDL.Func([IDL.Nat], [IDL.Vec(StreakEntry)], ['query']),
    'hostHeartbeat' : IDL.Func([IDL.Nat], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinSession' : IDL.Func([IDL.Text, IDL.Text], [JoinResult], []),
    'lockSession' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'removePlayer' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'setAutoAdvance' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'setProfile' : IDL.Func([IDL.Text], [], []),
    'startGame' : IDL.Func([IDL.Nat], [], []),
    'submitAnswer' : IDL.Func([IDL.Text, IDL.Nat, AnswerSubmission], [], []),
    'updatePlayerName' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'updateQuiz' : IDL.Func([IDL.Nat, IDL.Text, IDL.Vec(Question)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };