/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.1.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface QuestionResultsResponse {
    questionIndex: bigint;
    questionText: string;
    questionType: QuestionType;
    answerDistribution: Array<AnswerDistribution>;
    correctCount: bigint;
    options: Array<string>;
    totalAnswers: bigint;
}
export interface LeaderboardEntry {
    displayName: string;
    playerId: bigint;
    rank: bigint;
    score: bigint;
    currentStreak: bigint;
    avatarIndex: bigint;
}
export interface PostGameSummaryResponse {
    questionSummaries: Array<QuestionSummary>;
    totalPlayers: bigint;
    totalQuestions: bigint;
}
export interface Quiz {
    id: bigint;
    title: string;
    createdAt: bigint;
    updatedAt: bigint;
    questions: Array<Question>;
}
export interface Profile {
    name: string;
}
export interface Report {
    id: bigint;
    playedAt: bigint;
    playerCount: bigint;
    summary: PostGameSummaryResponse;
    players: Array<ArchivedPlayer>;
    questions: Array<ArchivedQuestion>;
    quizTitle: string;
    questionCount: bigint;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface AnswerDistribution {
    count: bigint;
    optionIndex: bigint;
    isCorrect: boolean;
}
export interface SessionInfo {
    roomPin: string;
    sessionId: bigint;
}
export interface ArchivedPlayer {
    displayName: string;
    answers: Array<ArchivedPlayerAnswer>;
    rank: bigint;
    score: bigint;
    avatarIndex: bigint;
}
export interface JoinResult {
    playerToken: bigint;
    playerId: bigint;
    sessionId: bigint;
    avatarIndex: bigint;
}
export interface LeaderboardResponse {
    totalPlayers: bigint;
    entries: Array<LeaderboardEntry>;
}
export interface ArchivedPlayerAnswer {
    selectedOptions: Array<bigint>;
    isCorrect: boolean;
    questionIndex: bigint;
    pointsEarned: bigint;
    sliderValue: bigint;
    textAnswer: string;
}
export type AnswerSubmission = {
    __kind__: "text";
    text: string;
} | {
    __kind__: "slider";
    slider: bigint;
} | {
    __kind__: "options";
    options: Array<bigint>;
};
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface StreakEntry {
    streak: bigint;
    displayName: string;
    avatarIndex: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface SessionStateResponse {
    status: SessionStatus;
    currentPhase: GamePhase;
    roomPin: string;
    playerCount: bigint;
    players: Array<PublicPlayerData>;
    answerCount: bigint;
    isLocked: boolean;
    sessionId: bigint;
    phaseStartTime: bigint;
    autoAdvance: boolean;
    currentQuestionIndex: bigint;
    currentQuestion?: HostQuestionData;
    questionCount: bigint;
}
export interface PublicPlayerData {
    displayName: string;
    playerId: bigint;
    score: bigint;
    avatarIndex: bigint;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface ReportSummary {
    id: bigint;
    playedAt: bigint;
    playerCount: bigint;
    quizTitle: string;
    questionCount: bigint;
}
export interface ArchivedQuestion {
    text: string;
    sliderMax: bigint;
    sliderMin: bigint;
    questionType: QuestionType;
    acceptedAnswers: Array<string>;
    options: Array<string>;
    sliderCorrect: bigint;
    correctOptionIndices: Array<bigint>;
}
export interface HostQuestionData {
    theme: string;
    pointMode: PointMode;
    timeLimit: bigint;
    text: string;
    sliderMax: bigint;
    sliderMin: bigint;
    questionType: QuestionType;
    image?: ExternalBlob;
    showQuestionToPlayers: boolean;
    acceptedAnswers: Array<string>;
    options: Array<string>;
    sliderCorrect: bigint;
    correctOptionIndices: Array<bigint>;
    imagePlacement: ImagePlacement;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface PlayerQuestionData {
    theme: string;
    timeLimit: bigint;
    text: string;
    sliderMax: bigint;
    sliderMin: bigint;
    questionType: QuestionType;
    image?: ExternalBlob;
    showQuestionToPlayers: boolean;
    options: Array<string>;
    imagePlacement: ImagePlacement;
}
export interface PlayerStateResponse {
    status: SessionStatus;
    currentPhase: GamePhase;
    ownScore: bigint;
    ownDisplayName: string;
    lastHostHeartbeat: bigint;
    playerCount: bigint;
    players: Array<PublicPlayerData>;
    hasAnsweredCurrent: boolean;
    isLocked: boolean;
    lastPointsEarned: bigint;
    phaseStartTime: bigint;
    ownAvatarIndex: bigint;
    currentQuestionIndex: bigint;
    currentStreak: bigint;
    currentQuestion?: PlayerQuestionData;
    lastAnswerCorrect?: boolean;
}
export interface Question {
    theme: string;
    pointMode: PointMode;
    timeLimit: bigint;
    text: string;
    isMultiSelect: boolean;
    sliderMax: bigint;
    sliderMin: bigint;
    questionType: QuestionType;
    image?: ExternalBlob;
    showQuestionToPlayers: boolean;
    acceptedAnswers: Array<string>;
    options: Array<string>;
    sliderCorrect: bigint;
    correctOptionIndices: Array<bigint>;
    imagePlacement: ImagePlacement;
}
export interface QuestionSummary {
    questionIndex: bigint;
    questionText: string;
    questionType: QuestionType;
    answerDistribution: Array<AnswerDistribution>;
    correctCount: bigint;
    correctPercent: bigint;
    options: Array<string>;
    totalAnswers: bigint;
}
export enum GamePhase {
    answering = "answering",
    scoreboard = "scoreboard",
    results = "results",
    ended = "ended",
    lobby = "lobby",
    questionDisplay = "questionDisplay",
    podium = "podium"
}
export enum ImagePlacement {
    background = "background",
    centered = "centered"
}
export enum PointMode {
    double_ = "double",
    none = "none",
    standard = "standard"
}
export enum QuestionType {
    quiz = "quiz",
    slider = "slider",
    typeAnswer = "typeAnswer",
    trueFalse = "trueFalse"
}
export enum SessionStatus {
    active = "active",
    ended = "ended",
    lobby = "lobby"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    advancePhase(sessionId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkRoomPin(roomPin: string): Promise<boolean>;
    createQuiz(title: string, questions: Array<Question>): Promise<bigint>;
    createSession(quizId: bigint): Promise<SessionInfo>;
    deleteQuiz(quizId: bigint): Promise<void>;
    deleteReport(reportId: bigint): Promise<void>;
    endSession(sessionId: bigint): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    getLeaderboard(sessionId: bigint): Promise<LeaderboardResponse>;
    getPlayerLeaderboard(roomPin: string, playerToken: bigint): Promise<LeaderboardResponse>;
    getPlayerQuestionResults(roomPin: string, playerToken: bigint, questionIndex: bigint): Promise<QuestionResultsResponse>;
    getPlayerState(roomPin: string, playerToken: bigint): Promise<PlayerStateResponse>;
    getPlayerStreaks(roomPin: string, playerToken: bigint): Promise<Array<StreakEntry>>;
    getPostGameSummary(sessionId: bigint): Promise<PostGameSummaryResponse>;
    getProfile(): Promise<Profile | null>;
    getQuestionResults(sessionId: bigint, questionIndex: bigint): Promise<QuestionResultsResponse>;
    getQuiz(quizId: bigint): Promise<Quiz | null>;
    getQuizzes(): Promise<Array<Quiz>>;
    getReport(reportId: bigint): Promise<Report | null>;
    getReports(): Promise<Array<ReportSummary>>;
    getSessionState(sessionId: bigint): Promise<SessionStateResponse>;
    getStreaks(sessionId: bigint): Promise<Array<StreakEntry>>;
    hostHeartbeat(sessionId: bigint): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    joinSession(roomPin: string, displayName: string): Promise<JoinResult>;
    lockSession(sessionId: bigint, locked: boolean): Promise<void>;
    removePlayer(sessionId: bigint, playerId: bigint): Promise<void>;
    setAutoAdvance(sessionId: bigint, enabled: boolean): Promise<void>;
    setProfile(name: string): Promise<void>;
    startGame(sessionId: bigint): Promise<void>;
    submitAnswer(roomPin: string, playerToken: bigint, answer: AnswerSubmission): Promise<void>;
    updatePlayerName(roomPin: string, playerToken: bigint, newName: string): Promise<void>;
    updateQuiz(quizId: bigint, title: string, questions: Array<Question>): Promise<void>;
}
import type { AnswerDistribution as _AnswerDistribution, AnswerSubmission as _AnswerSubmission, ArchivedPlayer as _ArchivedPlayer, ArchivedQuestion as _ArchivedQuestion, Error as _Error, ExternalBlob as _ExternalBlob, GamePhase as _GamePhase, HostQuestionData as _HostQuestionData, ImagePlacement as _ImagePlacement, PlayerQuestionData as _PlayerQuestionData, PlayerStateResponse as _PlayerStateResponse, PointMode as _PointMode, PostGameSummaryResponse as _PostGameSummaryResponse, Profile as _Profile, PublicPlayerData as _PublicPlayerData, Question as _Question, QuestionResultsResponse as _QuestionResultsResponse, QuestionSummary as _QuestionSummary, QuestionType as _QuestionType, Quiz as _Quiz, Report as _Report, Result as _Result, SessionStateResponse as _SessionStateResponse, SessionStatus as _SessionStatus, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async advancePhase(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.advancePhase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.advancePhase(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkRoomPin(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkRoomPin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkRoomPin(arg0);
            return result;
        }
    }
    async createQuiz(arg0: string, arg1: Array<Question>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createQuiz(arg0, await to_candid_vec_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createQuiz(arg0, await to_candid_vec_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createSession(arg0: bigint): Promise<SessionInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.createSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSession(arg0);
            return result;
        }
    }
    async deleteQuiz(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuiz(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuiz(arg0);
            return result;
        }
    }
    async deleteReport(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReport(arg0);
            return result;
        }
    }
    async endSession(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.endSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endSession(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(arg0: bigint): Promise<LeaderboardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard(arg0);
            return result;
        }
    }
    async getPlayerLeaderboard(arg0: string, arg1: bigint): Promise<LeaderboardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerLeaderboard(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerLeaderboard(arg0, arg1);
            return result;
        }
    }
    async getPlayerQuestionResults(arg0: string, arg1: bigint, arg2: bigint): Promise<QuestionResultsResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerQuestionResults(arg0, arg1, arg2);
                return from_candid_QuestionResultsResponse_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerQuestionResults(arg0, arg1, arg2);
            return from_candid_QuestionResultsResponse_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayerState(arg0: string, arg1: bigint): Promise<PlayerStateResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerState(arg0, arg1);
                return from_candid_PlayerStateResponse_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerState(arg0, arg1);
            return from_candid_PlayerStateResponse_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayerStreaks(arg0: string, arg1: bigint): Promise<Array<StreakEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerStreaks(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerStreaks(arg0, arg1);
            return result;
        }
    }
    async getPostGameSummary(arg0: bigint): Promise<PostGameSummaryResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostGameSummary(arg0);
                return from_candid_PostGameSummaryResponse_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostGameSummary(arg0);
            return from_candid_PostGameSummaryResponse_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuestionResults(arg0: bigint, arg1: bigint): Promise<QuestionResultsResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestionResults(arg0, arg1);
                return from_candid_QuestionResultsResponse_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestionResults(arg0, arg1);
            return from_candid_QuestionResultsResponse_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuiz(arg0: bigint): Promise<Quiz | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuiz(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuiz(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuizzes(): Promise<Array<Quiz>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizzes();
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizzes();
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReport(arg0: bigint): Promise<Report | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReport(arg0);
                return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReport(arg0);
            return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReports(): Promise<Array<ReportSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReports();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReports();
            return result;
        }
    }
    async getSessionState(arg0: bigint): Promise<SessionStateResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionState(arg0);
                return from_candid_SessionStateResponse_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionState(arg0);
            return from_candid_SessionStateResponse_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStreaks(arg0: bigint): Promise<Array<StreakEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStreaks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStreaks(arg0);
            return result;
        }
    }
    async hostHeartbeat(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.hostHeartbeat(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hostHeartbeat(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinSession(arg0: string, arg1: string): Promise<JoinResult> {
        if (this.processError) {
            try {
                const result = await this.actor.joinSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinSession(arg0, arg1);
            return result;
        }
    }
    async lockSession(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.lockSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.lockSession(arg0, arg1);
            return result;
        }
    }
    async removePlayer(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removePlayer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePlayer(arg0, arg1);
            return result;
        }
    }
    async setAutoAdvance(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAutoAdvance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAutoAdvance(arg0, arg1);
            return result;
        }
    }
    async setProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProfile(arg0);
            return result;
        }
    }
    async startGame(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startGame(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startGame(arg0);
            return result;
        }
    }
    async submitAnswer(arg0: string, arg1: bigint, arg2: AnswerSubmission): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAnswer(arg0, arg1, to_candid_AnswerSubmission_n69(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAnswer(arg0, arg1, to_candid_AnswerSubmission_n69(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updatePlayerName(arg0: string, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlayerName(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlayerName(arg0, arg1, arg2);
            return result;
        }
    }
    async updateQuiz(arg0: bigint, arg1: string, arg2: Array<Question>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuiz(arg0, arg1, await to_candid_vec_n14(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuiz(arg0, arg1, await to_candid_vec_n14(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_ArchivedQuestion_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ArchivedQuestion): ArchivedQuestion {
    return from_candid_record_n63(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_GamePhase_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GamePhase): GamePhase {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
async function from_candid_HostQuestionData_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HostQuestionData): Promise<HostQuestionData> {
    return await from_candid_record_n68(_uploadFile, _downloadFile, value);
}
function from_candid_ImagePlacement_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImagePlacement): ImagePlacement {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
async function from_candid_PlayerQuestionData_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerQuestionData): Promise<PlayerQuestionData> {
    return await from_candid_record_n38(_uploadFile, _downloadFile, value);
}
async function from_candid_PlayerStateResponse_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerStateResponse): Promise<PlayerStateResponse> {
    return await from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_PointMode_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PointMode): PointMode {
    return from_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function from_candid_PostGameSummaryResponse_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostGameSummaryResponse): PostGameSummaryResponse {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_QuestionResultsResponse_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionResultsResponse): QuestionResultsResponse {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_QuestionSummary_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionSummary): QuestionSummary {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_QuestionType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionType): QuestionType {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
async function from_candid_Question_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Promise<Question> {
    return await from_candid_record_n54(_uploadFile, _downloadFile, value);
}
async function from_candid_Quiz_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Quiz): Promise<Quiz> {
    return await from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_Report_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Report): Report {
    return from_candid_record_n60(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
async function from_candid_SessionStateResponse_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionStateResponse): Promise<SessionStateResponse> {
    return await from_candid_record_n65(_uploadFile, _downloadFile, value);
}
function from_candid_SessionStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionStatus): SessionStatus {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerQuestionData]): Promise<PlayerQuestionData | null> {
    return value.length === 0 ? null : await from_candid_PlayerQuestionData_n37(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Profile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Quiz]): Promise<Quiz | null> {
    return value.length === 0 ? null : await from_candid_Quiz_n50(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Report]): Report | null {
    return value.length === 0 ? null : from_candid_Report_n59(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HostQuestionData]): Promise<HostQuestionData | null> {
    return value.length === 0 ? null : await from_candid_HostQuestionData_n67(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    questionIndex: bigint;
    questionText: string;
    questionType: _QuestionType;
    answerDistribution: Array<_AnswerDistribution>;
    correctCount: bigint;
    options: Array<string>;
    totalAnswers: bigint;
}): {
    questionIndex: bigint;
    questionText: string;
    questionType: QuestionType;
    answerDistribution: Array<AnswerDistribution>;
    correctCount: bigint;
    options: Array<string>;
    totalAnswers: bigint;
} {
    return {
        questionIndex: value.questionIndex,
        questionText: value.questionText,
        questionType: from_candid_QuestionType_n28(_uploadFile, _downloadFile, value.questionType),
        answerDistribution: value.answerDistribution,
        correctCount: value.correctCount,
        options: value.options,
        totalAnswers: value.totalAnswers
    };
}
async function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _SessionStatus;
    currentPhase: _GamePhase;
    ownScore: bigint;
    ownDisplayName: string;
    lastHostHeartbeat: bigint;
    playerCount: bigint;
    players: Array<_PublicPlayerData>;
    hasAnsweredCurrent: boolean;
    isLocked: boolean;
    lastPointsEarned: bigint;
    phaseStartTime: bigint;
    ownAvatarIndex: bigint;
    currentQuestionIndex: bigint;
    currentStreak: bigint;
    currentQuestion: [] | [_PlayerQuestionData];
    lastAnswerCorrect: [] | [boolean];
}): Promise<{
    status: SessionStatus;
    currentPhase: GamePhase;
    ownScore: bigint;
    ownDisplayName: string;
    lastHostHeartbeat: bigint;
    playerCount: bigint;
    players: Array<PublicPlayerData>;
    hasAnsweredCurrent: boolean;
    isLocked: boolean;
    lastPointsEarned: bigint;
    phaseStartTime: bigint;
    ownAvatarIndex: bigint;
    currentQuestionIndex: bigint;
    currentStreak: bigint;
    currentQuestion?: PlayerQuestionData;
    lastAnswerCorrect?: boolean;
}> {
    return {
        status: from_candid_SessionStatus_n32(_uploadFile, _downloadFile, value.status),
        currentPhase: from_candid_GamePhase_n34(_uploadFile, _downloadFile, value.currentPhase),
        ownScore: value.ownScore,
        ownDisplayName: value.ownDisplayName,
        lastHostHeartbeat: value.lastHostHeartbeat,
        playerCount: value.playerCount,
        players: value.players,
        hasAnsweredCurrent: value.hasAnsweredCurrent,
        isLocked: value.isLocked,
        lastPointsEarned: value.lastPointsEarned,
        phaseStartTime: value.phaseStartTime,
        ownAvatarIndex: value.ownAvatarIndex,
        currentQuestionIndex: value.currentQuestionIndex,
        currentStreak: value.currentStreak,
        currentQuestion: record_opt_to_undefined(await from_candid_opt_n36(_uploadFile, _downloadFile, value.currentQuestion)),
        lastAnswerCorrect: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.lastAnswerCorrect))
    };
}
async function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    theme: string;
    timeLimit: bigint;
    text: string;
    sliderMax: bigint;
    sliderMin: bigint;
    questionType: _QuestionType;
    image: [] | [_ExternalBlob];
    showQuestionToPlayers: boolean;
    options: Array<string>;
    imagePlacement: _ImagePlacement;
}): Promise<{
    theme: string;
    timeLimit: bigint;
    text: string;
    sliderMax: bigint;
    sliderMin: bigint;
    questionType: QuestionType;
    image?: ExternalBlob;
    showQuestionToPlayers: boolean;
    options: Array<string>;
    imagePlacement: ImagePlacement;
}> {
    return {
        theme: value.theme,
        timeLimit: value.timeLimit,
        text: value.text,
        sliderMax: value.sliderMax,
        sliderMin: value.sliderMin,
        questionType: from_candid_QuestionType_n28(_uploadFile, _downloadFile, value.questionType),
        image: record_opt_to_undefined(await from_candid_opt_n39(_uploadFile, _downloadFile, value.image)),
        showQuestionToPlayers: value.showQuestionToPlayers,
        options: value.options,
        imagePlacement: from_candid_ImagePlacement_n41(_uploadFile, _downloadFile, value.imagePlacement)
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    questionSummaries: Array<_QuestionSummary>;
    totalPlayers: bigint;
    totalQuestions: bigint;
}): {
    questionSummaries: Array<QuestionSummary>;
    totalPlayers: bigint;
    totalQuestions: bigint;
} {
    return {
        questionSummaries: from_candid_vec_n45(_uploadFile, _downloadFile, value.questionSummaries),
        totalPlayers: value.totalPlayers,
        totalQuestions: value.totalQuestions
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    questionIndex: bigint;
    questionText: string;
    questionType: _QuestionType;
    answerDistribution: Array<_AnswerDistribution>;
    correctCount: bigint;
    correctPercent: bigint;
    options: Array<string>;
    totalAnswers: bigint;
}): {
    questionIndex: bigint;
    questionText: string;
    questionType: QuestionType;
    answerDistribution: Array<AnswerDistribution>;
    correctCount: bigint;
    correctPercent: bigint;
    options: Array<string>;
    totalAnswers: bigint;
} {
    return {
        questionIndex: value.questionIndex,
        questionText: value.questionText,
        questionType: from_candid_QuestionType_n28(_uploadFile, _downloadFile, value.questionType),
        answerDistribution: value.answerDistribution,
        correctCount: value.correctCount,
        correctPercent: value.correctPercent,
        options: value.options,
        totalAnswers: value.totalAnswers
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    createdAt: bigint;
    updatedAt: bigint;
    questions: Array<_Question>;
}): Promise<{
    id: bigint;
    title: string;
    createdAt: bigint;
    updatedAt: bigint;
    questions: Array<Question>;
}> {
    return {
        id: value.id,
        title: value.title,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        questions: await from_candid_vec_n52(_uploadFile, _downloadFile, value.questions)
    };
}
async function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    theme: string;
    pointMode: _PointMode;
    timeLimit: bigint;
    text: string;
    isMultiSelect: boolean;
    sliderMax: bigint;
    sliderMin: bigint;
    questionType: _QuestionType;
    image: [] | [_ExternalBlob];
    showQuestionToPlayers: boolean;
    acceptedAnswers: Array<string>;
    options: Array<string>;
    sliderCorrect: bigint;
    correctOptionIndices: Array<bigint>;
    imagePlacement: _ImagePlacement;
}): Promise<{
    theme: string;
    pointMode: PointMode;
    timeLimit: bigint;
    text: string;
    isMultiSelect: boolean;
    sliderMax: bigint;
    sliderMin: bigint;
    questionType: QuestionType;
    image?: ExternalBlob;
    showQuestionToPlayers: boolean;
    acceptedAnswers: Array<string>;
    options: Array<string>;
    sliderCorrect: bigint;
    correctOptionIndices: Array<bigint>;
    imagePlacement: ImagePlacement;
}> {
    return {
        theme: value.theme,
        pointMode: from_candid_PointMode_n55(_uploadFile, _downloadFile, value.pointMode),
        timeLimit: value.timeLimit,
        text: value.text,
        isMultiSelect: value.isMultiSelect,
        sliderMax: value.sliderMax,
        sliderMin: value.sliderMin,
        questionType: from_candid_QuestionType_n28(_uploadFile, _downloadFile, value.questionType),
        image: record_opt_to_undefined(await from_candid_opt_n39(_uploadFile, _downloadFile, value.image)),
        showQuestionToPlayers: value.showQuestionToPlayers,
        acceptedAnswers: value.acceptedAnswers,
        options: value.options,
        sliderCorrect: value.sliderCorrect,
        correctOptionIndices: value.correctOptionIndices,
        imagePlacement: from_candid_ImagePlacement_n41(_uploadFile, _downloadFile, value.imagePlacement)
    };
}
function from_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    playedAt: bigint;
    playerCount: bigint;
    summary: _PostGameSummaryResponse;
    players: Array<_ArchivedPlayer>;
    questions: Array<_ArchivedQuestion>;
    quizTitle: string;
    questionCount: bigint;
}): {
    id: bigint;
    playedAt: bigint;
    playerCount: bigint;
    summary: PostGameSummaryResponse;
    players: Array<ArchivedPlayer>;
    questions: Array<ArchivedQuestion>;
    quizTitle: string;
    questionCount: bigint;
} {
    return {
        id: value.id,
        playedAt: value.playedAt,
        playerCount: value.playerCount,
        summary: from_candid_PostGameSummaryResponse_n43(_uploadFile, _downloadFile, value.summary),
        players: value.players,
        questions: from_candid_vec_n61(_uploadFile, _downloadFile, value.questions),
        quizTitle: value.quizTitle,
        questionCount: value.questionCount
    };
}
function from_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: string;
    sliderMax: bigint;
    sliderMin: bigint;
    questionType: _QuestionType;
    acceptedAnswers: Array<string>;
    options: Array<string>;
    sliderCorrect: bigint;
    correctOptionIndices: Array<bigint>;
}): {
    text: string;
    sliderMax: bigint;
    sliderMin: bigint;
    questionType: QuestionType;
    acceptedAnswers: Array<string>;
    options: Array<string>;
    sliderCorrect: bigint;
    correctOptionIndices: Array<bigint>;
} {
    return {
        text: value.text,
        sliderMax: value.sliderMax,
        sliderMin: value.sliderMin,
        questionType: from_candid_QuestionType_n28(_uploadFile, _downloadFile, value.questionType),
        acceptedAnswers: value.acceptedAnswers,
        options: value.options,
        sliderCorrect: value.sliderCorrect,
        correctOptionIndices: value.correctOptionIndices
    };
}
async function from_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _SessionStatus;
    currentPhase: _GamePhase;
    roomPin: string;
    playerCount: bigint;
    players: Array<_PublicPlayerData>;
    answerCount: bigint;
    isLocked: boolean;
    sessionId: bigint;
    phaseStartTime: bigint;
    autoAdvance: boolean;
    currentQuestionIndex: bigint;
    currentQuestion: [] | [_HostQuestionData];
    questionCount: bigint;
}): Promise<{
    status: SessionStatus;
    currentPhase: GamePhase;
    roomPin: string;
    playerCount: bigint;
    players: Array<PublicPlayerData>;
    answerCount: bigint;
    isLocked: boolean;
    sessionId: bigint;
    phaseStartTime: bigint;
    autoAdvance: boolean;
    currentQuestionIndex: bigint;
    currentQuestion?: HostQuestionData;
    questionCount: bigint;
}> {
    return {
        status: from_candid_SessionStatus_n32(_uploadFile, _downloadFile, value.status),
        currentPhase: from_candid_GamePhase_n34(_uploadFile, _downloadFile, value.currentPhase),
        roomPin: value.roomPin,
        playerCount: value.playerCount,
        players: value.players,
        answerCount: value.answerCount,
        isLocked: value.isLocked,
        sessionId: value.sessionId,
        phaseStartTime: value.phaseStartTime,
        autoAdvance: value.autoAdvance,
        currentQuestionIndex: value.currentQuestionIndex,
        currentQuestion: record_opt_to_undefined(await from_candid_opt_n66(_uploadFile, _downloadFile, value.currentQuestion)),
        questionCount: value.questionCount
    };
}
async function from_candid_record_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    theme: string;
    pointMode: _PointMode;
    timeLimit: bigint;
    text: string;
    sliderMax: bigint;
    sliderMin: bigint;
    questionType: _QuestionType;
    image: [] | [_ExternalBlob];
    showQuestionToPlayers: boolean;
    acceptedAnswers: Array<string>;
    options: Array<string>;
    sliderCorrect: bigint;
    correctOptionIndices: Array<bigint>;
    imagePlacement: _ImagePlacement;
}): Promise<{
    theme: string;
    pointMode: PointMode;
    timeLimit: bigint;
    text: string;
    sliderMax: bigint;
    sliderMin: bigint;
    questionType: QuestionType;
    image?: ExternalBlob;
    showQuestionToPlayers: boolean;
    acceptedAnswers: Array<string>;
    options: Array<string>;
    sliderCorrect: bigint;
    correctOptionIndices: Array<bigint>;
    imagePlacement: ImagePlacement;
}> {
    return {
        theme: value.theme,
        pointMode: from_candid_PointMode_n55(_uploadFile, _downloadFile, value.pointMode),
        timeLimit: value.timeLimit,
        text: value.text,
        sliderMax: value.sliderMax,
        sliderMin: value.sliderMin,
        questionType: from_candid_QuestionType_n28(_uploadFile, _downloadFile, value.questionType),
        image: record_opt_to_undefined(await from_candid_opt_n39(_uploadFile, _downloadFile, value.image)),
        showQuestionToPlayers: value.showQuestionToPlayers,
        acceptedAnswers: value.acceptedAnswers,
        options: value.options,
        sliderCorrect: value.sliderCorrect,
        correctOptionIndices: value.correctOptionIndices,
        imagePlacement: from_candid_ImagePlacement_n41(_uploadFile, _downloadFile, value.imagePlacement)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    quiz: null;
} | {
    slider: null;
} | {
    typeAnswer: null;
} | {
    trueFalse: null;
}): QuestionType {
    return "quiz" in value ? QuestionType.quiz : "slider" in value ? QuestionType.slider : "typeAnswer" in value ? QuestionType.typeAnswer : "trueFalse" in value ? QuestionType.trueFalse : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    ended: null;
} | {
    lobby: null;
}): SessionStatus {
    return "active" in value ? SessionStatus.active : "ended" in value ? SessionStatus.ended : "lobby" in value ? SessionStatus.lobby : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    answering: null;
} | {
    scoreboard: null;
} | {
    results: null;
} | {
    ended: null;
} | {
    lobby: null;
} | {
    questionDisplay: null;
} | {
    podium: null;
}): GamePhase {
    return "answering" in value ? GamePhase.answering : "scoreboard" in value ? GamePhase.scoreboard : "results" in value ? GamePhase.results : "ended" in value ? GamePhase.ended : "lobby" in value ? GamePhase.lobby : "questionDisplay" in value ? GamePhase.questionDisplay : "podium" in value ? GamePhase.podium : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    background: null;
} | {
    centered: null;
}): ImagePlacement {
    return "background" in value ? ImagePlacement.background : "centered" in value ? ImagePlacement.centered : value;
}
function from_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    double: null;
} | {
    none: null;
} | {
    standard: null;
}): PointMode {
    return "double" in value ? PointMode.double : "none" in value ? PointMode.none : "standard" in value ? PointMode.standard : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n10(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QuestionSummary>): Array<QuestionSummary> {
    return value.map((x)=>from_candid_QuestionSummary_n46(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Question>): Promise<Array<Question>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Question_n53(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Quiz>): Promise<Array<Quiz>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Quiz_n50(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ArchivedQuestion>): Array<ArchivedQuestion> {
    return value.map((x)=>from_candid_ArchivedQuestion_n62(_uploadFile, _downloadFile, x));
}
function to_candid_AnswerSubmission_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnswerSubmission): _AnswerSubmission {
    return to_candid_variant_n70(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_ImagePlacement_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ImagePlacement): _ImagePlacement {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_PointMode_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PointMode): _PointMode {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_QuestionType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionType): _QuestionType {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
async function to_candid_Question_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Question): Promise<_Question> {
    return await to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    theme: string;
    pointMode: PointMode;
    timeLimit: bigint;
    text: string;
    isMultiSelect: boolean;
    sliderMax: bigint;
    sliderMin: bigint;
    questionType: QuestionType;
    image?: ExternalBlob;
    showQuestionToPlayers: boolean;
    acceptedAnswers: Array<string>;
    options: Array<string>;
    sliderCorrect: bigint;
    correctOptionIndices: Array<bigint>;
    imagePlacement: ImagePlacement;
}): Promise<{
    theme: string;
    pointMode: _PointMode;
    timeLimit: bigint;
    text: string;
    isMultiSelect: boolean;
    sliderMax: bigint;
    sliderMin: bigint;
    questionType: _QuestionType;
    image: [] | [_ExternalBlob];
    showQuestionToPlayers: boolean;
    acceptedAnswers: Array<string>;
    options: Array<string>;
    sliderCorrect: bigint;
    correctOptionIndices: Array<bigint>;
    imagePlacement: _ImagePlacement;
}> {
    return {
        theme: value.theme,
        pointMode: to_candid_PointMode_n17(_uploadFile, _downloadFile, value.pointMode),
        timeLimit: value.timeLimit,
        text: value.text,
        isMultiSelect: value.isMultiSelect,
        sliderMax: value.sliderMax,
        sliderMin: value.sliderMin,
        questionType: to_candid_QuestionType_n19(_uploadFile, _downloadFile, value.questionType),
        image: value.image ? candid_some(await to_candid_ExternalBlob_n21(_uploadFile, _downloadFile, value.image)) : candid_none(),
        showQuestionToPlayers: value.showQuestionToPlayers,
        acceptedAnswers: value.acceptedAnswers,
        options: value.options,
        sliderCorrect: value.sliderCorrect,
        correctOptionIndices: value.correctOptionIndices,
        imagePlacement: to_candid_ImagePlacement_n22(_uploadFile, _downloadFile, value.imagePlacement)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PointMode): {
    double: null;
} | {
    none: null;
} | {
    standard: null;
} {
    return value == PointMode.double ? {
        double_: null
    } : value == PointMode.none ? {
        none: null
    } : value == PointMode.standard ? {
        standard: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionType): {
    quiz: null;
} | {
    slider: null;
} | {
    typeAnswer: null;
} | {
    trueFalse: null;
} {
    return value == QuestionType.quiz ? {
        quiz: null
    } : value == QuestionType.slider ? {
        slider: null
    } : value == QuestionType.typeAnswer ? {
        typeAnswer: null
    } : value == QuestionType.trueFalse ? {
        trueFalse: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ImagePlacement): {
    background: null;
} | {
    centered: null;
} {
    return value == ImagePlacement.background ? {
        background: null
    } : value == ImagePlacement.centered ? {
        centered: null
    } : value;
}
function to_candid_variant_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "text";
    text: string;
} | {
    __kind__: "slider";
    slider: bigint;
} | {
    __kind__: "options";
    options: Array<bigint>;
}): {
    text: string;
} | {
    slider: bigint;
} | {
    options: Array<bigint>;
} {
    return value.__kind__ === "text" ? {
        text: value.text
    } : value.__kind__ === "slider" ? {
        slider: value.slider
    } : value.__kind__ === "options" ? {
        options: value.options
    } : value;
}
async function to_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Question>): Promise<Array<_Question>> {
    return await Promise.all(value.map(async (x)=>await to_candid_Question_n15(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
